server:
  error:
    include-stacktrace: never
    include-message: always
spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: 1qaz!QAZ
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
springdoc:
  show-login-endpoint: true

login:
  secret: bleich
  token-expiration-in-min: 15